// <auto-generated />
// FHIR R4 Resource: Claim
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// A provider issued list of professional services and products which have been provided, or are to be provided, to a patient which is sent to an insurer for reimbursement.
/// </summary>
public class Claim : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "Claim";

    /// <summary>
    /// Business Identifier for claim
    /// </summary>
    [JsonPropertyName("identifier")]
    public List<Identifier>? IdentifierValue { get; set; }

    /// <summary>
    /// active | cancelled | draft | entered-in-error
    /// </summary>
    [Required]
    [JsonPropertyName("status")]
    public FhirCode Status { get; set; }

    /// <summary>
    /// Category or discipline
    /// </summary>
    [Required]
    [JsonPropertyName("type")]
    public CodeableConcept Type { get; set; }

    /// <summary>
    /// More granular claim type
    /// </summary>
    [JsonPropertyName("subType")]
    public CodeableConcept SubType { get; set; }

    /// <summary>
    /// claim | preauthorization | predetermination
    /// </summary>
    [Required]
    [JsonPropertyName("use")]
    public FhirCode Use { get; set; }

    /// <summary>
    /// The recipient of the products and services
    /// </summary>
    [Required]
    [JsonPropertyName("patient")]
    public Reference Patient { get; set; }

    /// <summary>
    /// Relevant time frame for the claim
    /// </summary>
    [JsonPropertyName("billablePeriod")]
    public Period BillablePeriod { get; set; }

    /// <summary>
    /// Resource creation date
    /// </summary>
    [Required]
    [JsonPropertyName("created")]
    public FhirDateTime Created { get; set; }

    /// <summary>
    /// Author of the claim
    /// </summary>
    [JsonPropertyName("enterer")]
    public Reference Enterer { get; set; }

    /// <summary>
    /// Target
    /// </summary>
    [JsonPropertyName("insurer")]
    public Reference Insurer { get; set; }

    /// <summary>
    /// Party responsible for the claim
    /// </summary>
    [Required]
    [JsonPropertyName("provider")]
    public Reference Provider { get; set; }

    /// <summary>
    /// Desired processing ugency
    /// </summary>
    [Required]
    [JsonPropertyName("priority")]
    public CodeableConcept Priority { get; set; }

    /// <summary>
    /// For whom to reserve funds
    /// </summary>
    [JsonPropertyName("fundsReserve")]
    public CodeableConcept FundsReserve { get; set; }

    /// <summary>
    /// Prior or corollary claims
    /// </summary>
    [JsonPropertyName("related")]
    public List<BackboneElement>? Related { get; set; }

    /// <summary>
    /// Reference to the related claim
    /// </summary>
    [JsonPropertyName("claim")]
    public Reference Claim { get; set; }

    /// <summary>
    /// How the reference claim is related
    /// </summary>
    [JsonPropertyName("relationship")]
    public CodeableConcept Relationship { get; set; }

    /// <summary>
    /// File or case reference
    /// </summary>
    [JsonPropertyName("reference")]
    public Identifier Reference { get; set; }

    /// <summary>
    /// Prescription authorizing services and products
    /// </summary>
    [JsonPropertyName("prescription")]
    public Reference Prescription { get; set; }

    /// <summary>
    /// Original prescription if superseded by fulfiller
    /// </summary>
    [JsonPropertyName("originalPrescription")]
    public Reference OriginalPrescription { get; set; }

    /// <summary>
    /// Recipient of benefits payable
    /// </summary>
    [JsonPropertyName("payee")]
    public BackboneElement Payee { get; set; }

    /// <summary>
    /// Category of recipient
    /// </summary>
    [Required]
    [JsonPropertyName("type")]
    public CodeableConcept Type { get; set; }

    /// <summary>
    /// Recipient reference
    /// </summary>
    [JsonPropertyName("party")]
    public Reference Party { get; set; }

    /// <summary>
    /// Treatment referral
    /// </summary>
    [JsonPropertyName("referral")]
    public Reference Referral { get; set; }

    /// <summary>
    /// Servicing facility
    /// </summary>
    [JsonPropertyName("facility")]
    public Reference Facility { get; set; }

    /// <summary>
    /// Members of the care team
    /// </summary>
    [JsonPropertyName("careTeam")]
    public List<BackboneElement>? CareTeam { get; set; }

    /// <summary>
    /// Order of care team
    /// </summary>
    [Required]
    [JsonPropertyName("sequence")]
    public FhirPositiveInt Sequence { get; set; }

    /// <summary>
    /// Practitioner or organization
    /// </summary>
    [Required]
    [JsonPropertyName("provider")]
    public Reference Provider { get; set; }

    /// <summary>
    /// Indicator of the lead practitioner
    /// </summary>
    [JsonPropertyName("responsible")]
    public FhirBoolean Responsible { get; set; }

    /// <summary>
    /// Function within the team
    /// </summary>
    [JsonPropertyName("role")]
    public CodeableConcept Role { get; set; }

    /// <summary>
    /// Practitioner credential or specialization
    /// </summary>
    [JsonPropertyName("qualification")]
    public CodeableConcept Qualification { get; set; }

    /// <summary>
    /// Supporting information
    /// </summary>
    [JsonPropertyName("supportingInfo")]
    public List<BackboneElement>? SupportingInfo { get; set; }

    /// <summary>
    /// Information instance identifier
    /// </summary>
    [Required]
    [JsonPropertyName("sequence")]
    public FhirPositiveInt Sequence { get; set; }

    /// <summary>
    /// Classification of the supplied information
    /// </summary>
    [Required]
    [JsonPropertyName("category")]
    public CodeableConcept Category { get; set; }

    /// <summary>
    /// Type of information
    /// </summary>
    [JsonPropertyName("code")]
    public CodeableConcept Code { get; set; }

    /// <summary>
    /// Explanation for the information
    /// </summary>
    [JsonPropertyName("reason")]
    public CodeableConcept Reason { get; set; }

    /// <summary>
    /// Pertinent diagnosis information
    /// </summary>
    [JsonPropertyName("diagnosis")]
    public List<BackboneElement>? Diagnosis { get; set; }

    /// <summary>
    /// Clinical procedures performed
    /// </summary>
    [JsonPropertyName("procedure")]
    public List<BackboneElement>? Procedure { get; set; }

    /// <summary>
    /// Patient insurance information
    /// </summary>
    [Required]
    [JsonPropertyName("insurance")]
    public List<BackboneElement> Insurance { get; set; }

    /// <summary>
    /// Details of the event
    /// </summary>
    [JsonPropertyName("accident")]
    public BackboneElement Accident { get; set; }

    /// <summary>
    /// When the incident occurred
    /// </summary>
    [Required]
    [JsonPropertyName("date")]
    public FhirDate DateValue { get; set; }

    /// <summary>
    /// The nature of the accident
    /// </summary>
    [JsonPropertyName("type")]
    public CodeableConcept Type { get; set; }

    /// <summary>
    /// Product or service provided
    /// </summary>
    [JsonPropertyName("item")]
    public List<BackboneElement>? Item { get; set; }

    /// <summary>
    /// Total claim cost
    /// </summary>
    [JsonPropertyName("total")]
    public Money Total { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
