// <auto-generated />
// FHIR R4 Resource: DocumentManifest
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// A collection of documents compiled for a purpose together with metadata that applies to the collection.
/// </summary>
public class DocumentManifest : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "DocumentManifest";

    /// <summary>
    /// Unique Identifier for the set of documents
    /// </summary>
    [JsonPropertyName("masterIdentifier")]
    public Identifier MasterIdentifier { get; set; }

    /// <summary>
    /// Other identifiers for the manifest
    /// </summary>
    [JsonPropertyName("identifier")]
    public List<Identifier>? IdentifierValue { get; set; }

    /// <summary>
    /// current | superseded | entered-in-error
    /// </summary>
    [Required]
    [JsonPropertyName("status")]
    public FhirCode Status { get; set; }

    /// <summary>
    /// Kind of document set
    /// </summary>
    [JsonPropertyName("type")]
    public CodeableConcept Type { get; set; }

    /// <summary>
    /// The subject of the set of documents
    /// </summary>
    [JsonPropertyName("subject")]
    public Reference Subject { get; set; }

    /// <summary>
    /// When this document manifest created
    /// </summary>
    [JsonPropertyName("created")]
    public FhirDateTime Created { get; set; }

    /// <summary>
    /// Who and/or what authored the DocumentManifest
    /// </summary>
    [JsonPropertyName("author")]
    public List<Reference>? Author { get; set; }

    /// <summary>
    /// Intended to get notified about this set of documents
    /// </summary>
    [JsonPropertyName("recipient")]
    public List<Reference>? Recipient { get; set; }

    /// <summary>
    /// The source system/application/software
    /// </summary>
    [JsonPropertyName("source")]
    public FhirUri Source { get; set; }

    /// <summary>
    /// Human-readable description (title)
    /// </summary>
    [JsonPropertyName("description")]
    public FhirString Description { get; set; }

    /// <summary>
    /// Items in manifest
    /// </summary>
    [Required]
    [JsonPropertyName("content")]
    public List<Reference> Content { get; set; }

    /// <summary>
    /// Related things
    /// </summary>
    [JsonPropertyName("related")]
    public List<BackboneElement>? Related { get; set; }

    /// <summary>
    /// Identifiers of things that are related
    /// </summary>
    [JsonPropertyName("identifier")]
    public Identifier IdentifierValue { get; set; }

    /// <summary>
    /// Related Resource
    /// </summary>
    [JsonPropertyName("ref")]
    public Reference Ref { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
