// <auto-generated />
// FHIR R4 Resource: Endpoint
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// The technical details of an endpoint that can be used for electronic services, such as for web services providing XDS.b or a REST endpoint for another FHIR server. This may include any security context information.
/// </summary>
public class Endpoint : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "Endpoint";

    /// <summary>
    /// Identifies this endpoint across multiple systems
    /// </summary>
    [JsonPropertyName("identifier")]
    public List<Identifier>? IdentifierValue { get; set; }

    /// <summary>
    /// active | suspended | error | off | entered-in-error | test
    /// </summary>
    [Required]
    [JsonPropertyName("status")]
    public FhirCode Status { get; set; }

    /// <summary>
    /// Protocol/Profile/Standard to be used with this endpoint connection
    /// </summary>
    [Required]
    [JsonPropertyName("connectionType")]
    public Coding ConnectionType { get; set; }

    /// <summary>
    /// A name that this endpoint can be identified by
    /// </summary>
    [JsonPropertyName("name")]
    public FhirString Name { get; set; }

    /// <summary>
    /// Organization that manages this endpoint (might not be the organization that exposes the endpoint)
    /// </summary>
    [JsonPropertyName("managingOrganization")]
    public Reference ManagingOrganization { get; set; }

    /// <summary>
    /// Contact details for source (e.g. troubleshooting)
    /// </summary>
    [JsonPropertyName("contact")]
    public List<ContactPoint>? Contact { get; set; }

    /// <summary>
    /// Interval the endpoint is expected to be operational
    /// </summary>
    [JsonPropertyName("period")]
    public Period PeriodValue { get; set; }

    /// <summary>
    /// The type of content that may be used at this endpoint (e.g. XDS Discharge summaries)
    /// </summary>
    [Required]
    [JsonPropertyName("payloadType")]
    public List<CodeableConcept> PayloadType { get; set; }

    /// <summary>
    /// Mimetype to send. If not specified, the content could be anything (including no payload, if the connectionType defined this)
    /// </summary>
    [JsonPropertyName("payloadMimeType")]
    public List<FhirCode>? PayloadMimeType { get; set; }

    /// <summary>
    /// The technical base address for connecting to this endpoint
    /// </summary>
    [Required]
    [JsonPropertyName("address")]
    public FhirUrl Address { get; set; }

    /// <summary>
    /// Usage depends on the channel type
    /// </summary>
    [JsonPropertyName("header")]
    public List<FhirString>? Header { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
