// <auto-generated />
// FHIR R4 Resource: EpisodeOfCare
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// An association between a patient and an organization / healthcare provider(s) during which time encounters may occur. The managing organization assumes a level of responsibility for the patient during this time.
/// </summary>
public class EpisodeOfCare : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "EpisodeOfCare";

    /// <summary>
    /// Business Identifier(s) relevant for this EpisodeOfCare
    /// </summary>
    [JsonPropertyName("identifier")]
    public List<Identifier>? IdentifierValue { get; set; }

    /// <summary>
    /// planned | waitlist | active | onhold | finished | cancelled | entered-in-error
    /// </summary>
    [Required]
    [JsonPropertyName("status")]
    public FhirCode Status { get; set; }

    /// <summary>
    /// Past list of status codes (the current status may be included to cover the start date of the status)
    /// </summary>
    [JsonPropertyName("statusHistory")]
    public List<BackboneElement>? StatusHistory { get; set; }

    /// <summary>
    /// planned | waitlist | active | onhold | finished | cancelled | entered-in-error
    /// </summary>
    [Required]
    [JsonPropertyName("status")]
    public FhirCode Status { get; set; }

    /// <summary>
    /// Duration the EpisodeOfCare was in the specified status
    /// </summary>
    [Required]
    [JsonPropertyName("period")]
    public Period PeriodValue { get; set; }

    /// <summary>
    /// Type/class  - e.g. specialist referral, disease management
    /// </summary>
    [JsonPropertyName("type")]
    public List<CodeableConcept>? Type { get; set; }

    /// <summary>
    /// The list of diagnosis relevant to this episode of care
    /// </summary>
    [JsonPropertyName("diagnosis")]
    public List<BackboneElement>? Diagnosis { get; set; }

    /// <summary>
    /// The patient who is the focus of this episode of care
    /// </summary>
    [Required]
    [JsonPropertyName("patient")]
    public Reference Patient { get; set; }

    /// <summary>
    /// Organization that assumes care
    /// </summary>
    [JsonPropertyName("managingOrganization")]
    public Reference ManagingOrganization { get; set; }

    /// <summary>
    /// Interval during responsibility is assumed
    /// </summary>
    [JsonPropertyName("period")]
    public Period PeriodValue { get; set; }

    /// <summary>
    /// Originating Referral Request(s)
    /// </summary>
    [JsonPropertyName("referralRequest")]
    public List<Reference>? ReferralRequest { get; set; }

    /// <summary>
    /// Care manager/care coordinator for the patient
    /// </summary>
    [JsonPropertyName("careManager")]
    public Reference CareManager { get; set; }

    /// <summary>
    /// Other practitioners facilitating this episode of care
    /// </summary>
    [JsonPropertyName("team")]
    public List<Reference>? Team { get; set; }

    /// <summary>
    /// The set of accounts that may be used for billing for this EpisodeOfCare
    /// </summary>
    [JsonPropertyName("account")]
    public List<Reference>? Account { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
