// <auto-generated />
// FHIR R4 Resource: ImplementationGuide
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// A set of rules of how a particular interoperability or standards problem is solved - typically through the use of FHIR resources. This resource is used to gather all the parts of an implementation guide into a logical whole and to publish a computable definition of all the parts.
/// </summary>
public class ImplementationGuide : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "ImplementationGuide";

    /// <summary>
    /// Canonical identifier for this implementation guide, represented as a URI (globally unique)
    /// </summary>
    [Required]
    [JsonPropertyName("url")]
    public FhirUri Url { get; set; }

    /// <summary>
    /// Business version of the implementation guide
    /// </summary>
    [JsonPropertyName("version")]
    public FhirString Version { get; set; }

    /// <summary>
    /// Name for this implementation guide (computer friendly)
    /// </summary>
    [Required]
    [JsonPropertyName("name")]
    public FhirString Name { get; set; }

    /// <summary>
    /// Name for this implementation guide (human friendly)
    /// </summary>
    [JsonPropertyName("title")]
    public FhirString Title { get; set; }

    /// <summary>
    /// draft | active | retired | unknown
    /// </summary>
    [Required]
    [JsonPropertyName("status")]
    public FhirCode Status { get; set; }

    /// <summary>
    /// For testing purposes, not real usage
    /// </summary>
    [JsonPropertyName("experimental")]
    public FhirBoolean Experimental { get; set; }

    /// <summary>
    /// Date last changed
    /// </summary>
    [JsonPropertyName("date")]
    public FhirDateTime Date { get; set; }

    /// <summary>
    /// Name of the publisher (organization or individual)
    /// </summary>
    [JsonPropertyName("publisher")]
    public FhirString Publisher { get; set; }

    /// <summary>
    /// Contact details for the publisher
    /// </summary>
    [JsonPropertyName("contact")]
    public List<ContactDetail>? Contact { get; set; }

    /// <summary>
    /// Natural language description of the implementation guide
    /// </summary>
    [JsonPropertyName("description")]
    public FhirMarkdown Description { get; set; }

    /// <summary>
    /// The context that the content is intended to support
    /// </summary>
    [JsonPropertyName("useContext")]
    public List<UsageContext>? UseContext { get; set; }

    /// <summary>
    /// Intended jurisdiction for implementation guide (if applicable)
    /// </summary>
    [JsonPropertyName("jurisdiction")]
    public List<CodeableConcept>? Jurisdiction { get; set; }

    /// <summary>
    /// Use and/or publishing restrictions
    /// </summary>
    [JsonPropertyName("copyright")]
    public FhirMarkdown Copyright { get; set; }

    /// <summary>
    /// NPM Package name for IG
    /// </summary>
    [Required]
    [JsonPropertyName("packageId")]
    public FhirId PackageId { get; set; }

    /// <summary>
    /// SPDX license code for this IG (or not-open-source)
    /// </summary>
    [JsonPropertyName("license")]
    public FhirCode License { get; set; }

    /// <summary>
    /// FHIR Version(s) this Implementation Guide targets
    /// </summary>
    [Required]
    [JsonPropertyName("fhirVersion")]
    public List<FhirCode> FhirVersion { get; set; }

    /// <summary>
    /// Another Implementation guide this depends on
    /// </summary>
    [JsonPropertyName("dependsOn")]
    public List<BackboneElement>? DependsOn { get; set; }

    /// <summary>
    /// Identity of the IG that this depends on
    /// </summary>
    [Required]
    [JsonPropertyName("uri")]
    public FhirCanonical Uri { get; set; }

    /// <summary>
    /// NPM Package name for IG this depends on
    /// </summary>
    [JsonPropertyName("packageId")]
    public FhirId PackageId { get; set; }

    /// <summary>
    /// Version of the IG
    /// </summary>
    [JsonPropertyName("version")]
    public FhirString Version { get; set; }

    /// <summary>
    /// Profiles that apply globally
    /// </summary>
    [JsonPropertyName("global")]
    public List<BackboneElement>? Global { get; set; }

    /// <summary>
    /// Type this profile applies to
    /// </summary>
    [Required]
    [JsonPropertyName("type")]
    public FhirCode Type { get; set; }

    /// <summary>
    /// Profile that all resources must conform to
    /// </summary>
    [Required]
    [JsonPropertyName("profile")]
    public FhirCanonical Profile { get; set; }

    /// <summary>
    /// Information needed to build the IG
    /// </summary>
    [JsonPropertyName("definition")]
    public BackboneElement Definition { get; set; }

    /// <summary>
    /// Grouping used to present related resources in the IG
    /// </summary>
    [JsonPropertyName("grouping")]
    public List<BackboneElement>? Grouping { get; set; }

    /// <summary>
    /// Resource in the implementation guide
    /// </summary>
    [Required]
    [JsonPropertyName("resource")]
    public List<BackboneElement> Resource { get; set; }

    /// <summary>
    /// Page/Section in the Guide
    /// </summary>
    [JsonPropertyName("page")]
    public BackboneElement Page { get; set; }

    /// <summary>
    /// Defines how IG is built by tools
    /// </summary>
    [JsonPropertyName("parameter")]
    public List<BackboneElement>? Parameter { get; set; }

    /// <summary>
    /// A template for building resources
    /// </summary>
    [JsonPropertyName("template")]
    public List<BackboneElement>? Template { get; set; }

    /// <summary>
    /// Information about an assembled IG
    /// </summary>
    [JsonPropertyName("manifest")]
    public BackboneElement Manifest { get; set; }

    /// <summary>
    /// Location of rendered implementation guide
    /// </summary>
    [JsonPropertyName("rendering")]
    public FhirUrl Rendering { get; set; }

    /// <summary>
    /// Resource in the implementation guide
    /// </summary>
    [Required]
    [JsonPropertyName("resource")]
    public List<BackboneElement> Resource { get; set; }

    /// <summary>
    /// HTML page within the parent IG
    /// </summary>
    [JsonPropertyName("page")]
    public List<BackboneElement>? Page { get; set; }

    /// <summary>
    /// Image within the IG
    /// </summary>
    [JsonPropertyName("image")]
    public List<FhirString>? Image { get; set; }

    /// <summary>
    /// Additional linkable file in IG
    /// </summary>
    [JsonPropertyName("other")]
    public List<FhirString>? Other { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
