// <auto-generated />
// FHIR R4 Resource: MedicinalProductContraindication
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// The clinical particulars - indications, contraindications etc. of a medicinal product, including for regulatory purposes.
/// </summary>
public class MedicinalProductContraindication : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "MedicinalProductContraindication";

    /// <summary>
    /// The medication for which this is an indication
    /// </summary>
    [JsonPropertyName("subject")]
    public List<Reference>? Subject { get; set; }

    /// <summary>
    /// The disease, symptom or procedure for the contraindication
    /// </summary>
    [JsonPropertyName("disease")]
    public CodeableConcept Disease { get; set; }

    /// <summary>
    /// The status of the disease or symptom for the contraindication
    /// </summary>
    [JsonPropertyName("diseaseStatus")]
    public CodeableConcept DiseaseStatus { get; set; }

    /// <summary>
    /// A comorbidity (concurrent condition) or coinfection
    /// </summary>
    [JsonPropertyName("comorbidity")]
    public List<CodeableConcept>? Comorbidity { get; set; }

    /// <summary>
    /// Information about the use of the medicinal product in relation to other therapies as part of the indication
    /// </summary>
    [JsonPropertyName("therapeuticIndication")]
    public List<Reference>? TherapeuticIndication { get; set; }

    /// <summary>
    /// Information about the use of the medicinal product in relation to other therapies described as part of the indication
    /// </summary>
    [JsonPropertyName("otherTherapy")]
    public List<BackboneElement>? OtherTherapy { get; set; }

    /// <summary>
    /// The type of relationship between the medicinal product indication or contraindication and another therapy
    /// </summary>
    [Required]
    [JsonPropertyName("therapyRelationshipType")]
    public CodeableConcept TherapyRelationshipType { get; set; }

    /// <summary>
    /// The population group to which this applies
    /// </summary>
    [JsonPropertyName("population")]
    public List<Population>? PopulationValue { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
