// <auto-generated />
// FHIR R4 Resource: MedicinalProductUndesirableEffect
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// Describe the undesirable effects of the medicinal product.
/// </summary>
public class MedicinalProductUndesirableEffect : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "MedicinalProductUndesirableEffect";

    /// <summary>
    /// The medication for which this is an indication
    /// </summary>
    [JsonPropertyName("subject")]
    public List<Reference>? Subject { get; set; }

    /// <summary>
    /// The symptom, condition or undesirable effect
    /// </summary>
    [JsonPropertyName("symptomConditionEffect")]
    public CodeableConcept SymptomConditionEffect { get; set; }

    /// <summary>
    /// Classification of the effect
    /// </summary>
    [JsonPropertyName("classification")]
    public CodeableConcept Classification { get; set; }

    /// <summary>
    /// The frequency of occurrence of the effect
    /// </summary>
    [JsonPropertyName("frequencyOfOccurrence")]
    public CodeableConcept FrequencyOfOccurrence { get; set; }

    /// <summary>
    /// The population group to which this applies
    /// </summary>
    [JsonPropertyName("population")]
    public List<Population>? PopulationValue { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
