// <auto-generated />
// FHIR R4 Resource: MedicinalProductIndication
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// Indication for the Medicinal Product.
/// </summary>
public class MedicinalProductIndication : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "MedicinalProductIndication";

    /// <summary>
    /// The medication for which this is an indication
    /// </summary>
    [JsonPropertyName("subject")]
    public List<Reference>? Subject { get; set; }

    /// <summary>
    /// The disease, symptom or procedure that is the indication for treatment
    /// </summary>
    [JsonPropertyName("diseaseSymptomProcedure")]
    public CodeableConcept DiseaseSymptomProcedure { get; set; }

    /// <summary>
    /// The status of the disease or symptom for which the indication applies
    /// </summary>
    [JsonPropertyName("diseaseStatus")]
    public CodeableConcept DiseaseStatus { get; set; }

    /// <summary>
    /// Comorbidity (concurrent condition) or co-infection as part of the indication
    /// </summary>
    [JsonPropertyName("comorbidity")]
    public List<CodeableConcept>? Comorbidity { get; set; }

    /// <summary>
    /// The intended effect, aim or strategy to be achieved by the indication
    /// </summary>
    [JsonPropertyName("intendedEffect")]
    public CodeableConcept IntendedEffect { get; set; }

    /// <summary>
    /// Timing or duration information as part of the indication
    /// </summary>
    [JsonPropertyName("duration")]
    public Quantity Duration { get; set; }

    /// <summary>
    /// Information about the use of the medicinal product in relation to other therapies described as part of the indication
    /// </summary>
    [JsonPropertyName("otherTherapy")]
    public List<BackboneElement>? OtherTherapy { get; set; }

    /// <summary>
    /// The type of relationship between the medicinal product indication or contraindication and another therapy
    /// </summary>
    [Required]
    [JsonPropertyName("therapyRelationshipType")]
    public CodeableConcept TherapyRelationshipType { get; set; }

    /// <summary>
    /// Describe the undesirable effects of the medicinal product
    /// </summary>
    [JsonPropertyName("undesirableEffect")]
    public List<Reference>? UndesirableEffect { get; set; }

    /// <summary>
    /// The population group to which this applies
    /// </summary>
    [JsonPropertyName("population")]
    public List<Population>? PopulationValue { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
