// <auto-generated />
// FHIR R4 Resource: Observation
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.Abstractions;
using Fhir.Support.Base;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// Measurements and simple assertions made about a patient, device or other subject.
/// </summary>
public class Observation : IDomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType => "Observation";

    /// <summary>
    /// Logical id of this artifact
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>
    /// A human-readable narrative
    /// </summary>
    [JsonPropertyName("text")]
    public object? Text { get; set; }

    /// <summary>
    /// Additional content defined by implementations
    /// </summary>
    [JsonPropertyName("extension")]
    public IList<object>? Extension { get; set; }

    /// <summary>
    /// Extensions that cannot be ignored
    /// </summary>
    [JsonPropertyName("modifierExtension")]
    public IList<object>? ModifierExtension { get; set; }

    /// <summary>
    /// Business Identifier for observation
    /// </summary>
    [JsonPropertyName("identifier")]
    public List<Identifier> IdentifierValue { get; set; }

    /// <summary>
    /// Fulfills plan, proposal or order
    /// </summary>
    [JsonPropertyName("basedOn")]
    public List<Reference> BasedOn { get; set; }

    /// <summary>
    /// Part of referenced event
    /// </summary>
    [JsonPropertyName("partOf")]
    public List<Reference> PartOf { get; set; }

    /// <summary>
    /// registered | preliminary | final | amended +
    /// </summary>
    [Required]
    [JsonPropertyName("status")]
    public FhirCode Status { get; set; }

    /// <summary>
    /// Classification of  type of observation
    /// </summary>
    [JsonPropertyName("category")]
    public List<CodeableConcept> Category { get; set; }

    /// <summary>
    /// Type of observation (code / type)
    /// </summary>
    [Required]
    [JsonPropertyName("code")]
    public CodeableConcept Code { get; set; }

    /// <summary>
    /// Who and/or what the observation is about
    /// </summary>
    [JsonPropertyName("subject")]
    public Reference Subject { get; set; }

    /// <summary>
    /// What the observation is about, when it is not about the subject of record
    /// </summary>
    [JsonPropertyName("focus")]
    public List<Reference> Focus { get; set; }

    /// <summary>
    /// Healthcare event during which this observation is made
    /// </summary>
    [JsonPropertyName("encounter")]
    public Reference Encounter { get; set; }

    /// <summary>
    /// Clinically relevant time/time-period for observation (dateTime)
    /// </summary>
    [JsonPropertyName("effectiveDateTime")]
    public FhirDateTime? EffectiveDateTime { get; set; }

    /// <summary>
    /// Clinically relevant time/time-period for observation (period)
    /// </summary>
    [JsonPropertyName("effectivePeriod")]
    public Period? EffectivePeriod { get; set; }

    /// <summary>
    /// Date/Time this version was made available
    /// </summary>
    [JsonPropertyName("issued")]
    public FhirInstant Issued { get; set; }

    /// <summary>
    /// Who is responsible for the observation
    /// </summary>
    [JsonPropertyName("performer")]
    public List<Reference> Performer { get; set; }

    /// <summary>
    /// Actual result (Quantity)
    /// </summary>
    [JsonPropertyName("valueQuantity")]
    public Quantity? ValueQuantity { get; set; }

    /// <summary>
    /// Actual result (string)
    /// </summary>
    [JsonPropertyName("valueString")]
    public FhirString? ValueString { get; set; }

    /// <summary>
    /// Why the result is missing
    /// </summary>
    [JsonPropertyName("dataAbsentReason")]
    public CodeableConcept DataAbsentReason { get; set; }

    /// <summary>
    /// High, low, normal, etc.
    /// </summary>
    [JsonPropertyName("interpretation")]
    public List<CodeableConcept> Interpretation { get; set; }

    /// <summary>
    /// Comments about the observation
    /// </summary>
    [JsonPropertyName("note")]
    public List<Annotation> Note { get; set; }

    /// <summary>
    /// Observed body part
    /// </summary>
    [JsonPropertyName("bodySite")]
    public CodeableConcept BodySite { get; set; }

    /// <summary>
    /// How it was done
    /// </summary>
    [JsonPropertyName("method")]
    public CodeableConcept Method { get; set; }

    /// <summary>
    /// Specimen used for this observation
    /// </summary>
    [JsonPropertyName("specimen")]
    public Reference Specimen { get; set; }

    /// <summary>
    /// (Measurement) Device
    /// </summary>
    [JsonPropertyName("device")]
    public Reference Device { get; set; }

    /// <summary>
    /// Provides guide for interpretation
    /// </summary>
    [JsonPropertyName("referenceRange")]
    public List<BackboneElement> ReferenceRange { get; set; }

    /// <summary>
    /// Low Range, if relevant
    /// </summary>
    [JsonPropertyName("low")]
    public Quantity Low { get; set; }

    /// <summary>
    /// High Range, if relevant
    /// </summary>
    [JsonPropertyName("high")]
    public Quantity High { get; set; }

    /// <summary>
    /// Reference range qualifier
    /// </summary>
    [JsonPropertyName("type")]
    public CodeableConcept Type { get; set; }

    /// <summary>
    /// Reference range population
    /// </summary>
    [JsonPropertyName("appliesTo")]
    public List<CodeableConcept> AppliesTo { get; set; }

    /// <summary>
    /// Applicable age range, if relevant
    /// </summary>
    [JsonPropertyName("age")]
    public Range Age { get; set; }

    /// <summary>
    /// Related resource that belongs to the Observation group
    /// </summary>
    [JsonPropertyName("hasMember")]
    public List<Reference> HasMember { get; set; }

    /// <summary>
    /// Related measurements the observation is made from
    /// </summary>
    [JsonPropertyName("derivedFrom")]
    public List<Reference> DerivedFrom { get; set; }

    /// <summary>
    /// Component results
    /// </summary>
    [JsonPropertyName("component")]
    public List<BackboneElement> Component { get; set; }

    /// <summary>
    /// Type of component observation (code / type)
    /// </summary>
    [Required]
    [JsonPropertyName("code")]
    public CodeableConcept Code { get; set; }

    /// <summary>
    /// Actual component result (Quantity)
    /// </summary>
    [JsonPropertyName("valueQuantity")]
    public Quantity? ValueQuantity { get; set; }

    /// <summary>
    /// Actual component result (string)
    /// </summary>
    [JsonPropertyName("valueString")]
    public FhirString? ValueString { get; set; }

    /// <summary>
    /// Why the component result is missing
    /// </summary>
    [JsonPropertyName("dataAbsentReason")]
    public CodeableConcept DataAbsentReason { get; set; }

    /// <summary>
    /// High, low, normal, etc.
    /// </summary>
    [JsonPropertyName("interpretation")]
    public List<CodeableConcept> Interpretation { get; set; }

    /// <summary>
    /// Provides guide for interpretation of component result
    /// </summary>
    [JsonPropertyName("referenceRange")]
    public List<> ReferenceRange { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
