// <auto-generated />
// FHIR R4 Resource: PaymentNotice
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// This resource provides the status of the payment for goods and services rendered, and the request and response resource references.
/// </summary>
public class PaymentNotice : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "PaymentNotice";

    /// <summary>
    /// Business Identifier for the payment noctice
    /// </summary>
    [JsonPropertyName("identifier")]
    public List<Identifier>? IdentifierValue { get; set; }

    /// <summary>
    /// active | cancelled | draft | entered-in-error
    /// </summary>
    [Required]
    [JsonPropertyName("status")]
    public FhirCode Status { get; set; }

    /// <summary>
    /// Request reference
    /// </summary>
    [JsonPropertyName("request")]
    public Reference Request { get; set; }

    /// <summary>
    /// Response reference
    /// </summary>
    [JsonPropertyName("response")]
    public Reference Response { get; set; }

    /// <summary>
    /// Creation date
    /// </summary>
    [Required]
    [JsonPropertyName("created")]
    public FhirDateTime Created { get; set; }

    /// <summary>
    /// Responsible practitioner
    /// </summary>
    [JsonPropertyName("provider")]
    public Reference Provider { get; set; }

    /// <summary>
    /// Payment reference
    /// </summary>
    [Required]
    [JsonPropertyName("payment")]
    public Reference Payment { get; set; }

    /// <summary>
    /// Payment or clearing date
    /// </summary>
    [JsonPropertyName("paymentDate")]
    public FhirDate PaymentDate { get; set; }

    /// <summary>
    /// Party being paid
    /// </summary>
    [JsonPropertyName("payee")]
    public Reference Payee { get; set; }

    /// <summary>
    /// Party being notified
    /// </summary>
    [Required]
    [JsonPropertyName("recipient")]
    public Reference Recipient { get; set; }

    /// <summary>
    /// Monetary amount of the payment
    /// </summary>
    [Required]
    [JsonPropertyName("amount")]
    public Money Amount { get; set; }

    /// <summary>
    /// Issued or cleared Status of the payment
    /// </summary>
    [JsonPropertyName("paymentStatus")]
    public CodeableConcept PaymentStatus { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
