// <auto-generated />
// FHIR R4 Resource: Person
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// Demographics and administrative information about a person independent of a specific health-related context.
/// </summary>
public class Person : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "Person";

    /// <summary>
    /// A human identifier for this person
    /// </summary>
    [JsonPropertyName("identifier")]
    public List<Identifier>? IdentifierValue { get; set; }

    /// <summary>
    /// A name associated with the person
    /// </summary>
    [JsonPropertyName("name")]
    public List<HumanName>? Name { get; set; }

    /// <summary>
    /// A contact detail for the person
    /// </summary>
    [JsonPropertyName("telecom")]
    public List<ContactPoint>? Telecom { get; set; }

    /// <summary>
    /// male | female | other | unknown
    /// </summary>
    [JsonPropertyName("gender")]
    public FhirCode Gender { get; set; }

    /// <summary>
    /// The date on which the person was born
    /// </summary>
    [JsonPropertyName("birthDate")]
    public FhirDate BirthDate { get; set; }

    /// <summary>
    /// One or more addresses for the person
    /// </summary>
    [JsonPropertyName("address")]
    public List<Address>? AddressValue { get; set; }

    /// <summary>
    /// Image of the person
    /// </summary>
    [JsonPropertyName("photo")]
    public Attachment Photo { get; set; }

    /// <summary>
    /// The organization that is the custodian of the person record
    /// </summary>
    [JsonPropertyName("managingOrganization")]
    public Reference ManagingOrganization { get; set; }

    /// <summary>
    /// This person&apos;s record is in active use
    /// </summary>
    [JsonPropertyName("active")]
    public FhirBoolean Active { get; set; }

    /// <summary>
    /// Link to a resource that concerns the same actual person
    /// </summary>
    [JsonPropertyName("link")]
    public List<BackboneElement>? Link { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
