// <auto-generated />
// FHIR R4 Resource: QuestionnaireResponse
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// A structured set of questions and their answers. The questions are ordered and grouped into coherent subsets, corresponding to the structure of the grouping of the questionnaire being responded to.
/// </summary>
public class QuestionnaireResponse : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "QuestionnaireResponse";

    /// <summary>
    /// Unique id for this set of answers
    /// </summary>
    [JsonPropertyName("identifier")]
    public Identifier IdentifierValue { get; set; }

    /// <summary>
    /// Request fulfilled by this QuestionnaireResponse
    /// </summary>
    [JsonPropertyName("basedOn")]
    public List<Reference>? BasedOn { get; set; }

    /// <summary>
    /// Part of this action
    /// </summary>
    [JsonPropertyName("partOf")]
    public List<Reference>? PartOf { get; set; }

    /// <summary>
    /// Form being answered
    /// </summary>
    [JsonPropertyName("questionnaire")]
    public FhirCanonical Questionnaire { get; set; }

    /// <summary>
    /// in-progress | completed | amended | entered-in-error | stopped
    /// </summary>
    [Required]
    [JsonPropertyName("status")]
    public FhirCode Status { get; set; }

    /// <summary>
    /// The subject of the questions
    /// </summary>
    [JsonPropertyName("subject")]
    public Reference Subject { get; set; }

    /// <summary>
    /// Encounter created as part of
    /// </summary>
    [JsonPropertyName("encounter")]
    public Reference Encounter { get; set; }

    /// <summary>
    /// Date the answers were gathered
    /// </summary>
    [JsonPropertyName("authored")]
    public FhirDateTime Authored { get; set; }

    /// <summary>
    /// Person who received and recorded the answers
    /// </summary>
    [JsonPropertyName("author")]
    public Reference Author { get; set; }

    /// <summary>
    /// The person who answered the questions
    /// </summary>
    [JsonPropertyName("source")]
    public Reference Source { get; set; }

    /// <summary>
    /// Groups and questions
    /// </summary>
    [JsonPropertyName("item")]
    public List<BackboneElement>? Item { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
