// <auto-generated />
// FHIR R4 Resource: ResearchStudy
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// A process where a researcher or organization plans and then executes a series of steps intended to increase the field of healthcare-related knowledge.  This includes studies of safety, efficacy, comparative effectiveness and other information about medications, devices, therapies and other interventional and investigative techniques.  A ResearchStudy involves the gathering of information about human or animal subjects.
/// </summary>
public class ResearchStudy : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "ResearchStudy";

    /// <summary>
    /// Business Identifier for study
    /// </summary>
    [JsonPropertyName("identifier")]
    public List<Identifier>? IdentifierValue { get; set; }

    /// <summary>
    /// Name for this study
    /// </summary>
    [JsonPropertyName("title")]
    public FhirString Title { get; set; }

    /// <summary>
    /// Steps followed in executing study
    /// </summary>
    [JsonPropertyName("protocol")]
    public List<Reference>? Protocol { get; set; }

    /// <summary>
    /// Part of larger study
    /// </summary>
    [JsonPropertyName("partOf")]
    public List<Reference>? PartOf { get; set; }

    /// <summary>
    /// active | administratively-completed | approved | closed-to-accrual | closed-to-accrual-and-intervention | completed | disapproved | in-review | temporarily-closed-to-accrual | temporarily-closed-to-accrual-and-intervention | withdrawn
    /// </summary>
    [Required]
    [JsonPropertyName("status")]
    public FhirCode Status { get; set; }

    /// <summary>
    /// treatment | prevention | diagnostic | supportive-care | screening | health-services-research | basic-science | device-feasibility
    /// </summary>
    [JsonPropertyName("primaryPurposeType")]
    public CodeableConcept PrimaryPurposeType { get; set; }

    /// <summary>
    /// n-a | early-phase-1 | phase-1 | phase-1-phase-2 | phase-2 | phase-2-phase-3 | phase-3 | phase-4
    /// </summary>
    [JsonPropertyName("phase")]
    public CodeableConcept Phase { get; set; }

    /// <summary>
    /// Classifications for the study
    /// </summary>
    [JsonPropertyName("category")]
    public List<CodeableConcept>? Category { get; set; }

    /// <summary>
    /// Drugs, devices, etc. under study
    /// </summary>
    [JsonPropertyName("focus")]
    public List<CodeableConcept>? Focus { get; set; }

    /// <summary>
    /// Condition being studied
    /// </summary>
    [JsonPropertyName("condition")]
    public List<CodeableConcept>? Condition { get; set; }

    /// <summary>
    /// Contact details for the study
    /// </summary>
    [JsonPropertyName("contact")]
    public List<ContactDetail>? Contact { get; set; }

    /// <summary>
    /// References and dependencies
    /// </summary>
    [JsonPropertyName("relatedArtifact")]
    public List<RelatedArtifact>? RelatedArtifactValue { get; set; }

    /// <summary>
    /// Used to search for the study
    /// </summary>
    [JsonPropertyName("keyword")]
    public List<CodeableConcept>? Keyword { get; set; }

    /// <summary>
    /// Geographic region(s) for study
    /// </summary>
    [JsonPropertyName("location")]
    public List<CodeableConcept>? Location { get; set; }

    /// <summary>
    /// What this is study doing
    /// </summary>
    [JsonPropertyName("description")]
    public FhirMarkdown Description { get; set; }

    /// <summary>
    /// Inclusion &amp; exclusion criteria
    /// </summary>
    [JsonPropertyName("enrollment")]
    public List<Reference>? Enrollment { get; set; }

    /// <summary>
    /// When the study began and ended
    /// </summary>
    [JsonPropertyName("period")]
    public Period PeriodValue { get; set; }

    /// <summary>
    /// Organization that initiates and is legally responsible for the study
    /// </summary>
    [JsonPropertyName("sponsor")]
    public Reference Sponsor { get; set; }

    /// <summary>
    /// Researcher who oversees multiple aspects of the study
    /// </summary>
    [JsonPropertyName("principalInvestigator")]
    public Reference PrincipalInvestigator { get; set; }

    /// <summary>
    /// Facility where study activities are conducted
    /// </summary>
    [JsonPropertyName("site")]
    public List<Reference>? Site { get; set; }

    /// <summary>
    /// accrual-goal-met | closed-due-to-toxicity | closed-due-to-lack-of-study-progress | temporarily-closed-per-study-design
    /// </summary>
    [JsonPropertyName("reasonStopped")]
    public CodeableConcept ReasonStopped { get; set; }

    /// <summary>
    /// Comments made about the study
    /// </summary>
    [JsonPropertyName("note")]
    public List<Annotation>? Note { get; set; }

    /// <summary>
    /// Defined path through the study for a subject
    /// </summary>
    [JsonPropertyName("arm")]
    public List<BackboneElement>? Arm { get; set; }

    /// <summary>
    /// Label for study arm
    /// </summary>
    [Required]
    [JsonPropertyName("name")]
    public FhirString Name { get; set; }

    /// <summary>
    /// Categorization of study arm
    /// </summary>
    [JsonPropertyName("type")]
    public CodeableConcept Type { get; set; }

    /// <summary>
    /// Short explanation of study path
    /// </summary>
    [JsonPropertyName("description")]
    public FhirString Description { get; set; }

    /// <summary>
    /// A goal for the study
    /// </summary>
    [JsonPropertyName("objective")]
    public List<BackboneElement>? Objective { get; set; }

    /// <summary>
    /// Label for the objective
    /// </summary>
    [JsonPropertyName("name")]
    public FhirString Name { get; set; }

    /// <summary>
    /// primary | secondary | exploratory
    /// </summary>
    [JsonPropertyName("type")]
    public CodeableConcept Type { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
