// <auto-generated />
// FHIR R4 Resource: ResearchElementDefinition
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// The ResearchElementDefinition resource describes a "PICO" element that knowledge (evidence, assertion, recommendation) is about.
/// </summary>
public class ResearchElementDefinition : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "ResearchElementDefinition";

    /// <summary>
    /// Canonical identifier for this research element definition, represented as a URI (globally unique)
    /// </summary>
    [JsonPropertyName("url")]
    public FhirUri Url { get; set; }

    /// <summary>
    /// Additional identifier for the research element definition
    /// </summary>
    [JsonPropertyName("identifier")]
    public List<Identifier>? IdentifierValue { get; set; }

    /// <summary>
    /// Business version of the research element definition
    /// </summary>
    [JsonPropertyName("version")]
    public FhirString Version { get; set; }

    /// <summary>
    /// Name for this research element definition (computer friendly)
    /// </summary>
    [JsonPropertyName("name")]
    public FhirString Name { get; set; }

    /// <summary>
    /// Name for this research element definition (human friendly)
    /// </summary>
    [JsonPropertyName("title")]
    public FhirString Title { get; set; }

    /// <summary>
    /// Title for use in informal contexts
    /// </summary>
    [JsonPropertyName("shortTitle")]
    public FhirString ShortTitle { get; set; }

    /// <summary>
    /// Subordinate title of the ResearchElementDefinition
    /// </summary>
    [JsonPropertyName("subtitle")]
    public FhirString Subtitle { get; set; }

    /// <summary>
    /// draft | active | retired | unknown
    /// </summary>
    [Required]
    [JsonPropertyName("status")]
    public FhirCode Status { get; set; }

    /// <summary>
    /// For testing purposes, not real usage
    /// </summary>
    [JsonPropertyName("experimental")]
    public FhirBoolean Experimental { get; set; }

    /// <summary>
    /// Date last changed
    /// </summary>
    [JsonPropertyName("date")]
    public FhirDateTime Date { get; set; }

    /// <summary>
    /// Name of the publisher (organization or individual)
    /// </summary>
    [JsonPropertyName("publisher")]
    public FhirString Publisher { get; set; }

    /// <summary>
    /// Contact details for the publisher
    /// </summary>
    [JsonPropertyName("contact")]
    public List<ContactDetail>? Contact { get; set; }

    /// <summary>
    /// Natural language description of the research element definition
    /// </summary>
    [JsonPropertyName("description")]
    public FhirMarkdown Description { get; set; }

    /// <summary>
    /// Used for footnotes or explanatory notes
    /// </summary>
    [JsonPropertyName("comment")]
    public List<FhirString>? Comment { get; set; }

    /// <summary>
    /// The context that the content is intended to support
    /// </summary>
    [JsonPropertyName("useContext")]
    public List<UsageContext>? UseContext { get; set; }

    /// <summary>
    /// Intended jurisdiction for research element definition (if applicable)
    /// </summary>
    [JsonPropertyName("jurisdiction")]
    public List<CodeableConcept>? Jurisdiction { get; set; }

    /// <summary>
    /// Why this research element definition is defined
    /// </summary>
    [JsonPropertyName("purpose")]
    public FhirMarkdown Purpose { get; set; }

    /// <summary>
    /// Describes the clinical usage of the ResearchElementDefinition
    /// </summary>
    [JsonPropertyName("usage")]
    public FhirString Usage { get; set; }

    /// <summary>
    /// Use and/or publishing restrictions
    /// </summary>
    [JsonPropertyName("copyright")]
    public FhirMarkdown Copyright { get; set; }

    /// <summary>
    /// When the research element definition was approved by publisher
    /// </summary>
    [JsonPropertyName("approvalDate")]
    public FhirDate ApprovalDate { get; set; }

    /// <summary>
    /// When the research element definition was last reviewed
    /// </summary>
    [JsonPropertyName("lastReviewDate")]
    public FhirDate LastReviewDate { get; set; }

    /// <summary>
    /// When the research element definition is expected to be used
    /// </summary>
    [JsonPropertyName("effectivePeriod")]
    public Period EffectivePeriod { get; set; }

    /// <summary>
    /// The category of the ResearchElementDefinition, such as Education, Treatment, Assessment, etc.
    /// </summary>
    [JsonPropertyName("topic")]
    public List<CodeableConcept>? Topic { get; set; }

    /// <summary>
    /// Who authored the content
    /// </summary>
    [JsonPropertyName("author")]
    public List<ContactDetail>? Author { get; set; }

    /// <summary>
    /// Who edited the content
    /// </summary>
    [JsonPropertyName("editor")]
    public List<ContactDetail>? Editor { get; set; }

    /// <summary>
    /// Who reviewed the content
    /// </summary>
    [JsonPropertyName("reviewer")]
    public List<ContactDetail>? Reviewer { get; set; }

    /// <summary>
    /// Who endorsed the content
    /// </summary>
    [JsonPropertyName("endorser")]
    public List<ContactDetail>? Endorser { get; set; }

    /// <summary>
    /// Additional documentation, citations, etc.
    /// </summary>
    [JsonPropertyName("relatedArtifact")]
    public List<RelatedArtifact>? RelatedArtifactValue { get; set; }

    /// <summary>
    /// Logic used by the ResearchElementDefinition
    /// </summary>
    [JsonPropertyName("library")]
    public List<FhirCanonical>? Library { get; set; }

    /// <summary>
    /// population | exposure | outcome
    /// </summary>
    [Required]
    [JsonPropertyName("type")]
    public FhirCode Type { get; set; }

    /// <summary>
    /// dichotomous | continuous | descriptive
    /// </summary>
    [JsonPropertyName("variableType")]
    public FhirCode VariableType { get; set; }

    /// <summary>
    /// What defines the members of the research element
    /// </summary>
    [Required]
    [JsonPropertyName("characteristic")]
    public List<BackboneElement> Characteristic { get; set; }

    /// <summary>
    /// What code/value pairs define members?
    /// </summary>
    [JsonPropertyName("usageContext")]
    public List<UsageContext>? UsageContextValue { get; set; }

    /// <summary>
    /// Whether the characteristic includes or excludes members
    /// </summary>
    [JsonPropertyName("exclude")]
    public FhirBoolean Exclude { get; set; }

    /// <summary>
    /// What unit is the outcome described in?
    /// </summary>
    [JsonPropertyName("unitOfMeasure")]
    public CodeableConcept UnitOfMeasure { get; set; }

    /// <summary>
    /// What time period does the study cover
    /// </summary>
    [JsonPropertyName("studyEffectiveDescription")]
    public FhirString StudyEffectiveDescription { get; set; }

    /// <summary>
    /// Observation time from study start
    /// </summary>
    [JsonPropertyName("studyEffectiveTimeFromStart")]
    public Duration StudyEffectiveTimeFromStart { get; set; }

    /// <summary>
    /// mean | median | mean-of-mean | mean-of-median | median-of-mean | median-of-median
    /// </summary>
    [JsonPropertyName("studyEffectiveGroupMeasure")]
    public FhirCode StudyEffectiveGroupMeasure { get; set; }

    /// <summary>
    /// What time period do participants cover
    /// </summary>
    [JsonPropertyName("participantEffectiveDescription")]
    public FhirString ParticipantEffectiveDescription { get; set; }

    /// <summary>
    /// Observation time from study start
    /// </summary>
    [JsonPropertyName("participantEffectiveTimeFromStart")]
    public Duration ParticipantEffectiveTimeFromStart { get; set; }

    /// <summary>
    /// mean | median | mean-of-mean | mean-of-median | median-of-mean | median-of-median
    /// </summary>
    [JsonPropertyName("participantEffectiveGroupMeasure")]
    public FhirCode ParticipantEffectiveGroupMeasure { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
