// <auto-generated />
// FHIR R4 Resource: SubstancePolymer
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// Todo.
/// </summary>
public class SubstancePolymer : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "SubstancePolymer";

    /// <summary>
    /// Todo
    /// </summary>
    [JsonPropertyName("class")]
    public CodeableConcept Class { get; set; }

    /// <summary>
    /// Todo
    /// </summary>
    [JsonPropertyName("geometry")]
    public CodeableConcept Geometry { get; set; }

    /// <summary>
    /// Todo
    /// </summary>
    [JsonPropertyName("copolymerConnectivity")]
    public List<CodeableConcept>? CopolymerConnectivity { get; set; }

    /// <summary>
    /// Todo
    /// </summary>
    [JsonPropertyName("modification")]
    public List<FhirString>? Modification { get; set; }

    /// <summary>
    /// Todo
    /// </summary>
    [JsonPropertyName("monomerSet")]
    public List<BackboneElement>? MonomerSet { get; set; }

    /// <summary>
    /// Todo
    /// </summary>
    [JsonPropertyName("ratioType")]
    public CodeableConcept RatioType { get; set; }

    /// <summary>
    /// Todo
    /// </summary>
    [JsonPropertyName("startingMaterial")]
    public List<BackboneElement>? StartingMaterial { get; set; }

    /// <summary>
    /// Todo
    /// </summary>
    [JsonPropertyName("repeat")]
    public List<BackboneElement>? Repeat { get; set; }

    /// <summary>
    /// Todo
    /// </summary>
    [JsonPropertyName("numberOfUnits")]
    public FhirInteger NumberOfUnits { get; set; }

    /// <summary>
    /// Todo
    /// </summary>
    [JsonPropertyName("averageMolecularFormula")]
    public FhirString AverageMolecularFormula { get; set; }

    /// <summary>
    /// Todo
    /// </summary>
    [JsonPropertyName("repeatUnitAmountType")]
    public CodeableConcept RepeatUnitAmountType { get; set; }

    /// <summary>
    /// Todo
    /// </summary>
    [JsonPropertyName("repeatUnit")]
    public List<BackboneElement>? RepeatUnit { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
