// <auto-generated />
// FHIR R4 Resource: SupplyRequest
// This file is automatically generated. Do not edit manually.

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Fhir.R4.Models.Base;
using Fhir.TypeFramework.DataTypes;

namespace Fhir.R4.Models.Resources;

/// <summary>
/// A record of a request for a medication, substance or device used in the healthcare setting.
/// </summary>
public class SupplyRequest : DomainResource
{
    /// <summary>
    /// Resource type name
    /// </summary>
    [JsonPropertyName("resourceType")]
    public override string ResourceType => "SupplyRequest";

    /// <summary>
    /// Business Identifier for SupplyRequest
    /// </summary>
    [JsonPropertyName("identifier")]
    public List<Identifier>? IdentifierValue { get; set; }

    /// <summary>
    /// draft | active | suspended +
    /// </summary>
    [JsonPropertyName("status")]
    public FhirCode Status { get; set; }

    /// <summary>
    /// The kind of supply (central, non-stock, etc.)
    /// </summary>
    [JsonPropertyName("category")]
    public CodeableConcept Category { get; set; }

    /// <summary>
    /// routine | urgent | asap | stat
    /// </summary>
    [JsonPropertyName("priority")]
    public FhirCode Priority { get; set; }

    /// <summary>
    /// The requested amount of the item indicated
    /// </summary>
    [Required]
    [JsonPropertyName("quantity")]
    public Quantity QuantityValue { get; set; }

    /// <summary>
    /// Ordered item details
    /// </summary>
    [JsonPropertyName("parameter")]
    public List<BackboneElement>? Parameter { get; set; }

    /// <summary>
    /// When the request was made
    /// </summary>
    [JsonPropertyName("authoredOn")]
    public FhirDateTime AuthoredOn { get; set; }

    /// <summary>
    /// Individual making the request
    /// </summary>
    [JsonPropertyName("requester")]
    public Reference Requester { get; set; }

    /// <summary>
    /// Who is intended to fulfill the request
    /// </summary>
    [JsonPropertyName("supplier")]
    public List<Reference>? Supplier { get; set; }

    /// <summary>
    /// The reason why the supply item was requested
    /// </summary>
    [JsonPropertyName("reasonCode")]
    public List<CodeableConcept>? ReasonCode { get; set; }

    /// <summary>
    /// The reason why the supply item was requested
    /// </summary>
    [JsonPropertyName("reasonReference")]
    public List<Reference>? ReasonReference { get; set; }

    /// <summary>
    /// The origin of the supply
    /// </summary>
    [JsonPropertyName("deliverFrom")]
    public Reference DeliverFrom { get; set; }

    /// <summary>
    /// The destination of the supply
    /// </summary>
    [JsonPropertyName("deliverTo")]
    public Reference DeliverTo { get; set; }

    /// <summary>
    /// Validates this instance according to FHIR rules
    /// </summary>
    public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        foreach (var result in base.Validate(validationContext))
            yield return result;

        // TODO: Add specific validation rules
    }

}
