using System.Text;
using Fhir.TypeFramework.Choices;

namespace FhirResourceCreator.Generation;

internal sealed record ChoiceEmitMember(string JsonName, string TypeSuffix, string ClrTypeName);

internal sealed class ChoiceEmitGroup(string elementName, IReadOnlyList<ChoiceEmitMember> members)
{
    public string ElementName { get; } = elementName;
    public IReadOnlyList<ChoiceEmitMember> Members { get; } = members;
}

internal static class ChoiceHelperCodeEmitter
{
    public static string Generate(string rootNamespace, IReadOnlyList<string> partialClassNames, IReadOnlyList<ChoiceEmitGroup> groups)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Fhir.TypeFramework.Choices;");
        sb.AppendLine("using Fhir.TypeFramework.DataTypes;");
        sb.AppendLine("using Fhir.TypeFramework.DataTypes.PrimitiveTypes;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace};");
        sb.AppendLine();
        EmitNestedOpen(sb, partialClassNames, 0);
        EmitChoiceMethods(sb, groups, indent: new string(' ', partialClassNames.Count * 4));
        EmitNestedClose(sb, partialClassNames, 0);
        return sb.ToString();
    }

    private static void EmitChoiceMethods(StringBuilder sb, IReadOnlyList<ChoiceEmitGroup> groups, string indent)
    {
        foreach (var group in groups.OrderBy(g => g.ElementName, StringComparer.Ordinal))
        {
            var stem = group.ElementName;
            var pascal = ToPascalStem(stem);
            sb.AppendLine($"{indent}/// <summary>取得 <c>{stem}</c> choice 目前作用中的值。</summary>");
            sb.AppendLine($"{indent}public object? Get{pascal}Choice() => ChoiceAccessor.GetValue(this, \"{stem}\");");
            sb.AppendLine();
            sb.AppendLine($"{indent}/// <summary>是否已設定 <c>{stem}</c> choice。</summary>");
            sb.AppendLine($"{indent}public bool Has{pascal} => ChoiceAccessor.HasValue(this, \"{stem}\");");
            sb.AppendLine();
            sb.AppendLine($"{indent}/// <summary>作用中變體的 FHIR 型別名稱（如 boolean、dateTime）。</summary>");
            sb.AppendLine($"{indent}public string? Get{pascal}ChoiceType() => ChoiceAccessor.GetActiveTypeName(this, \"{stem}\");");
            sb.AppendLine();
            sb.AppendLine($"{indent}/// <summary>清除 <c>{stem}</c> 全部 choice 變體。</summary>");
            sb.AppendLine($"{indent}public void Clear{pascal}() => ChoiceAccessor.Clear(this, \"{stem}\");");
            sb.AppendLine();

            var members = group.Members.OrderBy(m => m.JsonName, StringComparer.Ordinal).ToList();
            foreach (var member in members)
            {
                var methodName = GetSetterMethodName(pascal, member, members);
                var invocation = GetSetterInvocation(stem, member, members);
                sb.AppendLine($"{indent}/// <summary>設定 <c>{stem}</c> 為 <c>{member.TypeSuffix}</c>。</summary>");
                sb.AppendLine($"{indent}public void {methodName}({member.ClrTypeName} value) => {invocation};");
                sb.AppendLine();
            }
        }
    }

    private static void EmitNestedOpen(StringBuilder sb, IReadOnlyList<string> classNames, int index)
    {
        if (index >= classNames.Count) return;
        var indent = new string(' ', index * 4);
        sb.AppendLine($"{indent}public partial class {classNames[index]}");
        sb.AppendLine($"{indent}{{");
        EmitNestedOpen(sb, classNames, index + 1);
    }

    private static void EmitNestedClose(StringBuilder sb, IReadOnlyList<string> classNames, int index)
    {
        if (index >= classNames.Count) return;
        EmitNestedClose(sb, classNames, index + 1);
        var indent = new string(' ', index * 4);
        sb.AppendLine($"{indent}}}");
    }

    private static string GetSetterMethodName(string pascalStem, ChoiceEmitMember member, IReadOnlyList<ChoiceEmitMember> members)
    {
        if (members.Count(m => m.ClrTypeName == member.ClrTypeName) <= 1)
            return $"Set{pascalStem}";
        return $"Set{pascalStem}{ChoiceElementNaming.ToPascalStem(member.TypeSuffix)}";
    }

    private static string GetSetterInvocation(string stem, ChoiceEmitMember member, IReadOnlyList<ChoiceEmitMember> members)
    {
        if (members.Count(m => m.ClrTypeName == member.ClrTypeName) <= 1)
            return $"ChoiceAccessor.SetValue(this, \"{stem}\", value)";
        return $"ChoiceAccessor.SetValue(this, \"{stem}\", \"{member.TypeSuffix}\", value)";
    }

    private static string ToPascalStem(string fhirElementName)
        => ChoiceElementNaming.ToPascalStem(fhirElementName);
}
