using System.Text;
using FhirResourceCreator.Models;

namespace FhirResourceCreator.Generation;

/// <summary>為產生的資源寫出 ModelMetadata，供 Path／序列化／驗證共用。</summary>
public static class ModelMetadataEmitter
{
    public static string Generate(ResourceModel model, string rootNamespace)
    {
        var name = model.ResourceName ?? throw new InvalidOperationException("Resource name missing.");
        var elements = model.Elements?.Where(e => e.ParentPath == name && !e.IsSkip).ToList()
                       ?? [];

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Fhir.TypeFramework.Metadata;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {name}ModelMetadata");
        sb.AppendLine("{");
        sb.AppendLine("    public static ModelTypeMetadata Create() => new(");
        sb.AppendLine($"        \"{name}\",");
        sb.AppendLine($"        typeof({name}),");
        sb.AppendLine("        new ModelElementMetadata[]");
        sb.AppendLine("        {");
        foreach (var el in elements)
        {
            var jsonName = el.OriginalElementName ?? el.FinalElementName ?? "";
            var typeName = el.IsChoice ? "null" : $"\"{Escape(el.OriginalDataType ?? el.ClrTypeSimpleName)}\"";
            var choice = el.IsChoice
                ? $"new[] {{ {string.Join(", ", el.ChoiceTypeCodes.Select(c => $"\"{Escape(c)}\""))} }}"
                : "null";
            var min = el.IsMust ? 1 : 0;
            var max = el.IsMulti ? "*" : "1";
            sb.AppendLine(
                $"            new(\"{Escape(jsonName)}\", {typeName}, {Bool(el.IsMulti)}, {Bool(el.IsChoice)}, {choice}, {min}, \"{max}\"),");
        }

        sb.AppendLine("        });");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string Bool(bool value) => value ? "true" : "false";
}
